# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a67efae6ed2a10ec221a03880e22d53575228a7040a6f07ef53fb1dc64cac0e2c6e5bae40dad93365aff88efeccfa322a6325eb0d0e48032bb65cc68d36a1b25

test:
  secret_key_base: 67318042a9988aa496a12a297bba7dd18f528fa1006bac31d9d4eb0e3b71852ca195267ad6b9e509be7350b6778ad72602766619c2319e0affe6989b275fe5f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
